# Following settings can be defined app specific in the config.yaml file of the respective app
defaultSource: "file"           # for import of data and models
# file types that are allowed for import from Pandora ("ckan")
dataFileTypes:
  - "xlsx"
  - "xls"
  - "csv"
  - "odt"
  - "txt"
modelFileTypes:
  - "peitho"
  - "zip"
fileExtension:
  - "peitho"      # for download of models
  - "zip"
rPackageName: "PEITHO"       # for download and import of models

